name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
  
      - uses: actions/setup-node@v4
        with:
          node-version: 18

          
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        
      - name: Install Dependencies
        run: npm install
        
      - name: cypress-report
        uses: duynhanf/cypress-report@v2 
        
        with: 
         run: npx cypress run
         
      - name: Generate HTML Report
        run: npx multiple-cucumber-html-reporter --jsonDir=cypress/cucumber-json --reportPath=./reports/cucumber 
